Autocast tensor
tenstorrent/tt-train pull request #96
Opened 2024-11-01 17:42 UTC by rfurko-tt

### Description
Introduce `AutocastTensor` which can hold `ttnn::Tensor` as well as half precision copy of it (in case of `float32`).
Blocked by `tt-metal` issue [14825](https://github.com/tenstorrent/tt-metal/issues/14825)

### Changes Made
- [x] **New Feature:** Describe the new feature and its purpose.
- [ ] **Improvement:** Summarize the enhancements implemented.
- [ ] **Bug Fix:** Detail the issue that was addressed.
- [ ] **Refactor:** Outline any significant code refactoring efforts.

### Testing
- [x] Unit tests added or updated
- [x] Manual testing conducted

### Review Checklist
- [x] No breaking changes introduced
- [x] All tests pass successfully
- [x] Code complies with project style guidelines

2024-11-06 23:39 UTC, dmakoviichuk-tt commented on sources/ttml/autograd/autocast_tensor.hpp
> +    bool m_is_float32 = false;
a few months ago we had discussion when to use bool vs enums. We decided that almost never :)

2024-11-06 23:39 UTC, dmakoviichuk-tt commented on sources/ttml/autograd/autocast_tensor.hpp
> +    tt::tt_metal::Tensor &get_mutable_tensor(bool half_precision = true);
same point as above. But feel free to ignore it. I am not sure in bool vs enum.

2024-11-06 23:40 UTC, dmakoviichuk-tt commented on sources/ttml/core/tt_tensor_utils.cpp
> +// it is expected that tilize will be fixed in the after next tt-metal main update
did Naif fix it? if yes you can update it.

2024-11-06 23:42 UTC, dmakoviichuk-tt commented on sources/ttml/optimizers/sgd.cpp
> +            tensor_ptr->set_grad(core::zeros_like(tensor_ptr->get_value(/* half_precision */ false)));
if use enum you don't need to add comment about what this false means.

2024-11-06 23:43 UTC, dmakoviichuk-tt requested changes
Yeah please add ests and enums vs bool.
Overall is good.

2024-11-06 23:49 UTC, rfurko-tt commented on sources/ttml/core/tt_tensor_utils.cpp
> +// it is expected that tilize will be fixed in the after next tt-metal main update
not fixed yet
https://github.com/tenstorrent/tt-metal/issues/14570

2024-11-07 22:39 UTC, dmakoviichuk-tt approved these changes

2024-11-07 23:47 UTC, merged